"""Fixed Order table

Revision ID: 42ffdfe69c22
Revises: 626de03c1a8b
Create Date: 2024-11-11 20:31:25.628461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ffdfe69c22'
down_revision = '626de03c1a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('seat_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_number', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
