"""Created Order schema

Revision ID: 626de03c1a8b
Revises: 
Create Date: 2024-11-11 20:21:24.830125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626de03c1a8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('side_option_id', sa.Integer(), nullable=True),
    sa.Column('table_num', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('mods', sa.Text(), nullable=True),
    sa.Column('side_mods', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['side_option_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
